### PR TITLE
KH-381: Added NCD Screening form E2E tests.

### PR DESCRIPTION
**Pull request by kdaud**
Ticket → [KH-381](https://mekomsolutions.atlassian.net/browse/KH-381)

Description → This PR adds tests for NCD Screening form section;
- Medical history
- Investigations
- Life style
- Assessment
- Diagnosis
- Management

[KH-381]: https://mekomsolutions.atlassian.net/browse/KH-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Ruhanga — COMMENTED** [review]
Is the file named correctly?

`testHCScreeningForm.spec.ts` vs `testNCDScreeningForm.spec.ts`?

**Comment by kdaud** [comment]
> Is the file named correctly?

Probably yes.Checkout the form name [here](https://github.com/kdaud/ozone-distro-cambodia/blob/main/configs/openmrs_config/ampathformstranslations/Health%20Center%20-%20NCD%20Screening_translations_en.json#L4).

**Comment by kdaud** [comment]
@Ruhanga I'll create a different PR to rename all spec files.

**Comment by kdaud** [comment]
@Ruhanga we're good to go.

**Review by Ruhanga — APPROVED** [review]

**Pull request merged**
